version : 2.1

jobs:
  build:          
    steps:
      - checkout
      - run : python main.py
  test:
    docker:
      steps:
        - checkout
        - run : python test.py
  deploy:
    steps:
      - run : echo "Practical done"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - buil
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main





























        
           





















