version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9   # CircleCI official Python 3.9 image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

workflows:
  build_and_test:
    jobs:
      - build
